
select * from customer limit 5;

--Total revenue generated by men, woman
select gender, sum(purchase_amount_usd) from customer
group by gender

--Customers used discount and still spent more than average purchase amount
select customer_id, purchase_amount_usd from customer 
where discount_applied ='Yes' and
purchase_amount_usd > (select avg(purchase_amount_usd) from customer)

--Top 5 products with highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as av from customer
group by item_purchased
order by av desc 
limit 5

-- Compare avg purchase amt b/w standard and express shipping
select shipping_type, round(avg(purchase_amount_usd),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Compare avg spent b/w subscribers and non-subscribers
select subscription_status, count(1), round(avg(purchase_amount_usd),2) as avspent,
sum(purchase_amount_usd) as totspent from customer
group by subscription_status
order by totspent desc

--Which 5 products have highest percentage of purchases with discounts applied
select item_purchased,  round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(1),2) as perc from customer
where discount_applied ='Yes'
group by item_purchased
order by perc desc
limit 5

--Segment customers into new, returning, loyal based on total number of previous purchases and show count of each segment
select (case when previous_purchases=1 then 'New' when previous_purchases<=10 then 'Returning' else 'Loyal' end) as seg, count(1),sum(previous_purchases) as totprepur from customer
group by seg

--What are top 3 most purchased products within each category
select category, item_purchased, count(1) as cnt from customer
group by category, item_purchased
order by cnt desc
limit 3
